### ISSUE TITLE
Typos and grammar

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll-lang.github.io#5]
Notes from @sarastalla

> under "configuration and styles": 
> you end some bullets with periods, others without
> 
> under "themes and page layout": 
> - The theme option allows you to choose *diffent* stylesheets
> - Idyll currently ships with several page layouts that can be used to modify the structure of *how to* content is displayed on the page, allowing you to quickly test out different narrative styles for you project.
> 
> under "use idyll as an API": 
> - You can use Idyll directly from JavaScript as well. This is useful if you want to build on top of *Idyll,* for example, you could make a static blog engine that uses Idyll to compile the blog posts.
> ^ this comma should be a colon or semi-colon
> 
> under "built-in components":
> - All built-in *compononents* expose a property onEnteredView that can be used to trigger events when a reader scrolls the page to reveal specific content.
> 
> under "inline":
> - The inline component adds the display: inline-block style property, so that items inside of inline component will be displayed next to *eachother*. For example, this code,
> ^ bullets on this page need standardized punctuation, too

**Comment by sarastalla** [comment]
under "custom components":
- For example, a component can change the value of a property that it receives, and Idyll will *propegate* the change to any bound variables on the page.
^ should be propagate

under "refs":
- You've *leared* all about Idyll! All that's left is deploying you project to the web.
